version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/index.sql

  go-app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
